# Site settings
title: "Obehi Ikpea - Projects"
description: "A showcase of data science and biostatistics projects."
url: "https://obehiik.github.io"  # Your production URL
baseurl: ""  # Leave empty if publishing at the root

# Theme configuration
# You can use a Bootswatch theme like 'cosmo' by referencing it in your custom CSS or using a compatible Jekyll theme
theme: jekyll-theme-minimal

# Custom settings to mimic Quarto style
sass:
  style: compressed

# Navigation (if supported by your theme)
nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"

# Social and metadata
social:
  linkedin: "https://linkedin.com/in/obehi-ikpea-7b860a1b9/"
  github: "https://github.com/Obehiik"
  portfolio: "https://obehiikpea.quarto.pub/obehi-winnifred-ikpeas-data-science-portfolio/"
  email: "ikpeaobehi3@gmail.com"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown configuration
markdown: kramdown
kramdown:
  input: GFM

# Permalink structure for cleaner URLs
permalink: pretty
